################################# Basic configuration #########################
# Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL = "http://seifseit.de"
title = "seifseit"
theme = "airspace-hugo-1.1.0"
# Default time zone for time stamps; use any valid [tz database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List)
timeZone = "CET"
# Number of posts per page in list view
paginate = "4"
# Post excerpt length
summaryLength = "30"
# Disabled languages
disableLanguages = ["fr", "it"]
# Short name to enable Disqus comments
disqusShortname = "" # Get your shortname from here: https://disqus.com/profile/signup/
# Measurement ID (G-XXXXXXX) to enable Google Analytics
googleAnalytics = ""



############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.89.0"


################################# Output formats ##############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = [ "HTML" ]


################################# Markup ######################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false


################################# Default parameters ##########################
[params]
logo = "images/globe-detailed.svg"
logo_width = "80px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "usernaut"
image = "images/logo.svg" # this image will be used as fallback if a page has no image of its own

################################# Sidebar widgets #############################
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


################################# Contact page ################################
[params.contact]
# Address block
phone = ""
email = "demo@email.com" # TODO
location = """
**Dr. Jan Seifert**  
Im Vogelsang 20  
71638 Ludwigsburg  
Deutschland
"""
# Whether to display text descriptors (like "E-mail: ", "Phone: ") before the address block elements
address_descriptors = false

[params.contact.form]
enable = true
# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
use_netlify = false
# Form action
## Fill in your Form ID URL for Formspree.io, e.g. `https://formspree.io/f/{form_id}`
## Ignored if `use_netlify = true` (custom [success page](https://docs.netlify.com/forms/setup/#success-messages) is already included) 
action = "#"
# Image on custom success page `/message_sent.html`
success_image = "images/paper-plane.svg"


################################# Google map ##################################
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


################################# Preloader ###################################
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif image


################################# Cookies #####################################
[params.cookies]
enable = false
expire_days = 2


################################# counter.dev analytics #######################
# This is a [privacy-friendly alternative](https://counter.dev/privacy.html) to Google Analytics & Co.
[params.counter]
enable = true
# counter.dev username, see https://counter.dev/setup.html
username = ""


################################# Social Media ################################
# [[params.social]]
# icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/usernaut"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://de.linkedin.com/in/jan-seifert-3194951b1"

[[params.social]]
icon = "icon-seifseit-xing" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.xing.com/profile/Jan_Seifert7"

[[params.social]]
icon = "icon-seifseit-medium" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://medium.com/@jan.seifert"

[[params.social]]
icon = "icon-seifseit-researchgate" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.researchgate.net/profile/Jan-Seifert-2"




################################# Plugins #####################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


################################# English translation #########################
[languages.en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 2
copyright = "Copyright &copy; 2021 [Jan](https://www.seifseit.de). All Rights Reserved."

# Navigation menus
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
[[languages.en.menu.main]]
hasChildren = true
name = "More"
weight = 5


################################# French translation ##########################
[languages.fr]
languageName = "Français"
languageCode = "fr-FR"
contentDir = "content/french"
weight = 2
copyright = "Copyright &copy; 2021 [JAn](https://www.seifseit.de). Tous droits réservés."

# Navigation menus
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
[[languages.fr.menu.main]]
hasChildren = true
weight = 5
name = "Plus"


################################# Italian translation ##########################
[languages.it]
languageName = "Italiano"
languageCode = "it-IT"
contentDir = "content/italian"
weight = 2
copyright = "Copyright &copy; 2021 [Jan](https://www.seifseit.de). Tutti i diritti riservati."

# Navigation menus
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
[[languages.it.menu.main]]
hasChildren = true
weight = 5
name = "Più"


################################# German translation ##########################
[languages.de]
languageName = "Deutsch"
languageCode = "de-DE"
contentDir = "content/german"
weight = 1
copyright = "Copyright &copy; 2021 [Jan](https://www.seifseit.de). Alle Rechte vorbehalten."

# Navigation menus
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
[[languages.de.menu.main]]
hasChildren = true
name = "Mehr"
weight = 5
