################################# Basic configuration #########################
# Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL = "http://seifseit.de"
title = "seifseit"
theme = "airspace-hugo-1.1.0"
# Default time zone for time stamps; use any valid [tz database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List)
timeZone = "CET"
# Number of posts per page in list view
paginate = "6"
# Post excerpt length
summaryLength = "30"
# Languages
defaultContentLanguage = "de"
disableLanguages = [] 
# Short name to enable Disqus comments
disqusShortname = "" # Get your shortname from here: https://disqus.com/profile/signup/
# Measurement ID (G-XXXXXXX) to enable Google Analytics
googleAnalytics = ""



############################# Modules ##############################
[module.hugoVersion]
extended = true
min = "0.89.0"


################################ Output formats ###############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = ["HTML", "humanstxt" , "htaccess"]

[outputFormats]
[outputFormats.htaccess]
    baseName = ""
    isPlainText = true
    mediaType = "text/htaccess" # see media types

[outputFormats.humanstxt]
    baseName = "humans"
    isPlainText = true
    mediaType = "text/plain"


########################### NON DEFAULT MEDIA TYPES ############################
[mediaTypes]
  [mediaTypes."text/htaccess"]
    suffixes = ["htaccess"]


################################# Frontmatter ##################################
# Documentation: https://gohugo.io/getting-started/configuration/#configure-front-matter
[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']


#################################### Markup ####################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false



################################# Taxonomies ######################################
[taxonomies]
  category = "categories"
  language = "languages"
  tag = "tags"
  
#type = "types"
#project = "projects"


################################# Default parameters ##########################
[params]
logo = "images/globe-detailed.svg"
logo_width = "80px"
# OpenGraph / Twitter Card metadata
description = "Jan Seifert: User Experience Design Lead, Organisations- und Behavioural Design."
author = "Jan Seifert"
image = "images/logo.svg" # this image will be used as fallback if a page has no image of its own

################################# Sidebar widgets #############################
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
writingssidebar = ["taxonomy_category", "taxonomy_tags", "taxonomy_languages"] #"recent_writings", 

################################# Contact page ################################
[params.contact]
# Address block
phone = ""
email = "admin@seifseit.de"
location = """
**Dr. Jan Seifert**  
Im Vogelsang 20  
71638 Ludwigsburg  
Deutschland
"""
# Whether to display text descriptors (like "E-mail: ", "Phone: ") before the address block elements
address_descriptors = false

[params.contact.form]
enable = true
# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
use_netlify = false
# Form action
## Fill in your Form ID URL for Formspree.io, e.g. `https://formspree.io/f/{form_id}`
## Ignored if `use_netlify = true` (custom [success page](https://docs.netlify.com/forms/setup/#success-messages) is already included) 
action = "#"
# Image on custom success page `/message_sent.html`
success_image = "images/paper-plane.svg"


################################# Google map ##################################
[params.gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "48.888187"
map_longitude = "9.201936"
map_marker = "images/marker.png"


################################# Preloader ###################################
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif image


################################# Cookies #####################################
[params.cookies]
enable = false
expire_days = 2


################################# counter.dev analytics #######################
# This is a [privacy-friendly alternative](https://counter.dev/privacy.html) to Google Analytics & Co.
[params.counter]
enable = true
# counter.dev username, see https://counter.dev/setup.html
username = ""


################################# Social Media ################################
# [[params.social]]
# icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
# link = "#"

[[params.social]]
icon = "icon-seifseit-mastodon" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://sueden.social/@usernaut"
alt = "Mastodon"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "www.linkedin.com/in/jan-seifert-changitor"
alt = "Linked In"

[[params.social]]
icon = "icon-seifseit-xing" #
link = "https://www.xing.com/profile/Jan_Seifert7"
alt = "Xing"

[[params.social]]
icon = "icon-seifseit-medium" #
link = "https://medium.com/@jan.seifert"
alt = "Medium.com"

[[params.social]]
icon = "icon-seifseit-researchgate" #
link = "https://www.researchgate.net/profile/Jan-Seifert-2"
alt = "Research Gate"

[[params.social]]
icon = "icon-seifseit-gcupa"
link = "https://germanupa.de/profile/6932"
alt = "User Experience Professionals Association"


################################# humans.txt #####################################
[author]
  name = 'Jan Seifert'
  email = 'admin@seifseit.de'
  location = 'Ludwigsburg, Germany'


################################# Plugins #####################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"



[languages]

################################# English translation #########################
[languages.en]
languageName = "English"
languageCode = "en-GB"
contentDir = "content/english"
weight = 2

[languages.en.params]
copyrightowner = "by [Jan Seifert](/)."
rightsreserved = "All Rights Reserved."

# Navigation menus
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
[[languages.en.menu.main]]
hasChildren = true
name = "Works"
weight = 5




################################# German translation ##########################
[languages.de]
languageName = "Deutsch"
languageCode = "de-DE"
contentDir = "content/german"
weight = 1

[languages.de.params]
copyrightowner = "von [Jan Seifert](/)."
rightsreserved = "Alle Rechte vorbehalten."

# Navigation menus
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
[[languages.de.menu.main]]
hasChildren = true
name = "Arbeiten"
weight = 5
